#!/bin/bash
# Athor Vengada Kandasamy - S3727817 - S3727817@student.rmit.edu.au
# This script will allow the user to read some basic information about their device, such as
# The amount of Free Memory, Disk Usage, Connection information and Load Averages

# using the following parameters the user will see specific information to that parameter
# -f will display the free memory on the system
# -d will display the amount of space occupied and free on the system
# -c will display the connection information of the system
# -s will display the load average
# -l will display all the above information


#detect parameters
while getopts "fdcsl" flag ; do
	#output based on parameter
	case $flag in
		"f") 	#output the free memory information
			free -h --si | awk '/Mem/ {printf "\nFree Memory = %s\n", $4}' ;;

		"d")	#could use df / for just root system, however not doing so will allow for other devices to be show as well
			echo " " #spacing for more readable output
			df -h --si | awk '!/tmp/ {printf $1 "\t" $2 "\t" $3 "\t" $4 "\n"}' ;;

		"c") 	#output all connection information
			echo " " #spacing for more readable output
			ifconfig -a ;;

		"s") 	#get the uptime information and display its 1, 5 and 15min times
			uptime | awk '/load/ {print "Load Average - 1Min: " $8 " 5Min: " $9 " 15Min: " $10 }' ;;

		"l") 	#recursively call this script but with all parameters to display all the info
			echo " " #style
			./baseinfo -f -d -c -s ;; #carefull not to call -l which will cause infinite loop

		*) 	#If the parameter is not one of the above, inform the user
			echo invalid chocie $REPLY
	esac
done
