#!/bin/bash
# Athor Vengada Kandasamy - S3727817 - S3727817@student.rmit.edu.au
# This script will allow the user to read some basic information about their device, such as
# The amount of Free Memory, Disk Usage, Connection information and Load Averages

# using the following parameters the user will see specific information to that parameter
# -f will display the free memory on the system
# -d will display the amount of space occupied and free on the system
# -c will display the connection information of the system
# -s will display the load average
# -l will display all the above information


#detect parameters
while getopts "fdcsl" flag ; do
	case $flag in
		"f") free -h --si | awk '/Mem/ {printf "\nFree Memory = %s\n", $4}' ;;
		"d")	echo " " #could use "df /" for just root system, however not doing so will allow for other devices, such as usb to be shown as well
			df -h --si | awk '!/tmp/ {printf $1 "\t" $2 "\t" $3 "\t" $4 "\n"}' ;;
		"c") 	echo " "
			ifconfig -a ;;
		"s") uptime | awk '/load/ {print "Load Average - 1Min: " $8 " 5Min: " $9 " 15Min: " $10 }' ;;
		"l") 	echo " "
			./baseinfo -f -d -c -s ;; #carefull not to call -l which will cause infinite loop
		*) echo invalid chocie $REPLY
	esac
done
